apiVersion: v1
kind: BuildConfig
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "sample-image:latest"
  source:
    git:
      uri: {{ .Values.git }}
    sourceSecret:
      name: "basicsecret"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "python-33-centos7:latest"
